- name: Dev Environment
  hosts: localhost
  tasks:
    - name: Homebrew
      ansible.builtin.import_tasks: tasks/homebrew.yaml
      tags:
        - install

    - name: Aerospace
      ansible.builtin.import_tasks: tasks/aerospace.yaml
      tags:
        - install

    - name: Ghostty
      ansible.builtin.import_tasks: tasks/ghostty.yaml
      tags:
        - install

    - name: Tmux
      ansible.builtin.import_tasks: tasks/tmux.yaml
      tags:
        - install

    - name: Neovim
      ansible.builtin.import_tasks: tasks/neovim.yaml
      tags:
        - install

    - name: Tools
      ansible.builtin.import_tasks: tasks/tools.yaml
      tags:
        - install

    - name: Rust
      ansible.builtin.import_tasks: tasks/rust.yaml
      tags:
        - install

    - name: Zsh
      ansible.builtin.import_tasks: tasks/zsh.yaml
      tags:
        - install

    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yaml
      tags:
        - dotfiles
